// Helpers shared by the inverter firmware source dialog (HomeView) and the
// firmware upload card in ConfigAdminView: fetching the GitHub manifest,
// downloading an image into the browser and uploading it to the DTU.

import type { FirmwareManifest } from '@/types/FirmwareManifest';
import { authHeader } from '@/utils/authentication';

// Manifest generated by tools/gen_firmware_manifest.py on the firmware branch.
export const FIRMWARE_MANIFEST_URL =
    'https://raw.githubusercontent.com/xX-nichtlachen-Xx/OpenDTU/FirmwareUpdate_HM_IV/Firmware/manifest.json';

// Top 16 bits of the upper serial half, as used by the DTU's identity rules
// (lookupFirmwareSerialRule in src/WebApi_devinfo.cpp), as upper-case hex.
export function firmwareSerialPrefix(serial: string): string {
    return serial.padStart(12, '0').substring(0, 4).toUpperCase();
}

export function formatByteSize(bytes: number): string {
    if (bytes < 1024) {
        return `${bytes} B`;
    }
    return `${(bytes / 1024).toFixed(1)} KB`;
}

export async function fetchFirmwareManifest(url: string = FIRMWARE_MANIFEST_URL): Promise<FirmwareManifest> {
    const response = await fetch(url, { cache: 'no-cache' });
    if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
    }
    const manifest = (await response.json()) as FirmwareManifest;
    if (!Array.isArray(manifest.files) || typeof manifest.base_url !== 'string') {
        throw new Error('invalid manifest');
    }
    return manifest;
}

export function firmwareDownloadUrl(manifest: FirmwareManifest, path: string): string {
    return manifest.base_url + path.split('/').map(encodeURIComponent).join('/');
}

// Downloads a firmware image as raw bytes (so the size can be compared with
// the manifest byte for byte) and reports progress in percent when the server
// sends a Content-Length.
export function downloadFirmwareFile(url: string, onProgress?: (percent: number) => void): Promise<ArrayBuffer> {
    return new Promise((resolve, reject) => {
        const request = new XMLHttpRequest();
        request.responseType = 'arraybuffer';
        request.addEventListener('load', () => {
            if (request.status === 200 && request.response instanceof ArrayBuffer) {
                resolve(request.response);
            } else {
                reject(new Error(`HTTP ${request.status}`));
            }
        });
        request.addEventListener('error', () => reject(new Error('network')));
        request.addEventListener('abort', () => reject(new Error('aborted')));
        request.addEventListener('progress', (e) => {
            if (onProgress && e.lengthComputable && e.total > 0) {
                onProgress(Math.trunc((e.loaded / e.total) * 100));
            }
        });
        request.open('get', url);
        request.send();
    });
}

export class FirmwareUploadError extends Error {
    status: number;
    constructor(status: number, message: string) {
        super(message);
        this.status = status;
    }
}

// Uploads an image into the DTU's firmware buffer (PSRAM or inactive OTA slot)
// via the existing /api/file/upload endpoint. Rejects with FirmwareUploadError
// (status 0 = transport failure) whose message is the DTU's response text, if any.
export function uploadInverterFirmware(
    data: Blob,
    origName: string,
    onProgress?: (percent: number) => void
): Promise<void> {
    return new Promise((resolve, reject) => {
        const request = new XMLHttpRequest();
        request.addEventListener('load', () => {
            if (request.status === 200) {
                resolve();
            } else {
                reject(new FirmwareUploadError(request.status, request.responseText || ''));
            }
        });
        request.addEventListener('error', () => reject(new FirmwareUploadError(0, '')));
        request.addEventListener('abort', () => reject(new FirmwareUploadError(0, '')));
        request.upload.addEventListener('progress', (e) => {
            if (onProgress && e.total > 0) {
                onProgress(Math.trunc((e.loaded / e.total) * 100));
            }
        });
        request.withCredentials = true;

        const formData = new FormData();
        formData.append('firmware', data, 'firmware.hex');
        request.open(
            'post',
            '/api/file/upload?file=firmware/uploaded.hex&restart=false&origName=' + encodeURIComponent(origName)
        );
        authHeader().forEach((value, key) => {
            request.setRequestHeader(key, value);
        });
        request.send(formData);
    });
}
